#data Normalisation 
#Methods are simple feature scaling,Min-Max,z-Score or Standard Score
#Simple Feature scaling   x(new)=x(old)/xmax   Result =0 to 1
#Min Max    x(nex)=(x(old)-x(min))/(x(max)-x(min))  result=0 to 1
# z-Score x(new)=(x(old) -mu)/sigma)        mu=Average of feature  and sigma - Standard deviation   Result =-3 to 3

In [1]:
import pandas as pd
import numpy as np
path ="C:/Users/Guggi/Desktop/data analysis 1.xlsx"
df =pd.read_excel(path)
print(df)

    S. No     A   B   C     D   E  Length
0       1   2.0   1   5   3.0   4    45.0
1       2   4.0   3  10   6.0   8    43.0
2       3   6.0   5  15   9.0  12    66.0
3       4   8.0   7  20  12.0  16    78.0
4       5  10.0   9  25  15.0  20    32.0
5       6  12.0  11  30  18.0  24    12.0
6       7  14.0  13  35  21.0  28    54.0
7       8  16.0  15  40  24.0  32    67.0
8       9  18.0  17  45  27.0  36    77.0
9      10  20.0  19  50  30.0  40    89.0
10     11   NaN  21  55   NaN  44     NaN

In [2]:
df.head()

   S. No     A  B   C     D   E  Length
0      1   2.0  1   5   3.0   4    45.0
1      2   4.0  3  10   6.0   8    43.0
2      3   6.0  5  15   9.0  12    66.0
3      4   8.0  7  20  12.0  16    78.0
4      5  10.0  9  25  15.0  20    32.0

In [5]:
df.columns

Index(['S. No', 'A', 'B', 'C', 'D', 'E', 'Length'], dtype='object')

In [9]:
headers=["S.No","Even","Odd","Multiple of 5","Multiple of 3","Multiple of 4","Length"]
df.columns=headers
print(df)

    S.No  Even  Odd  Multiple of 5  Multiple of 3  Multiple of 4  Length
0      1   2.0    1              5            3.0              4    45.0
1      2   4.0    3             10            6.0              8    43.0
2      3   6.0    5             15            9.0             12    66.0
3      4   8.0    7             20           12.0             16    78.0
4      5  10.0    9             25           15.0             20    32.0
5      6  12.0   11             30           18.0             24    12.0
6      7  14.0   13             35           21.0             28    54.0
7      8  16.0   15             40           24.0             32    67.0
8      9  18.0   17             45           27.0             36    77.0
9     10  20.0   19             50           30.0             40    89.0
10    11   NaN   21             55            NaN             44     NaN

In [14]:
#Simple Feature scaling   x(new)=x(old)/xmax   Result =0 to 1
df["Length"]=df["Length"]/df["Length"].max()
df.head()

   S.No  Even  Odd  Multiple of 5  Multiple of 3  Multiple of 4    Length
0     1   2.0    1              5            3.0              4  0.505618
1     2   4.0    3             10            6.0              8  0.483146
2     3   6.0    5             15            9.0             12  0.741573
3     4   8.0    7             20           12.0             16  0.876404
4     5  10.0    9             25           15.0             20  0.359551

In [15]:
#Min Max    x(new)=(x(old)-x(min))/(x(max)-x(min))  result=0 to 1
path ="C:/Users/Guggi/Desktop/data analysis 1.xlsx"
df =pd.read_excel(path)
print(df)

    S. No     A   B   C     D   E  Length
0       1   2.0   1   5   3.0   4    45.0
1       2   4.0   3  10   6.0   8    43.0
2       3   6.0   5  15   9.0  12    66.0
3       4   8.0   7  20  12.0  16    78.0
4       5  10.0   9  25  15.0  20    32.0
5       6  12.0  11  30  18.0  24    12.0
6       7  14.0  13  35  21.0  28    54.0
7       8  16.0  15  40  24.0  32    67.0
8       9  18.0  17  45  27.0  36    77.0
9      10  20.0  19  50  30.0  40    89.0
10     11   NaN  21  55   NaN  44     NaN

In [19]:
#Min Max    x(new)=(x(old)-x(min))/(x(max)-x(min))  result=0 to 1
df["Length"]=(df["Length"]-df["Length"].min())/(df["Length"].max()-df["Length"].min())
print(df)

    S. No     A   B   C     D   E    Length
0       1   2.0   1   5   3.0   4  0.428571
1       2   4.0   3  10   6.0   8  0.402597
2       3   6.0   5  15   9.0  12  0.701299
3       4   8.0   7  20  12.0  16  0.857143
4       5  10.0   9  25  15.0  20  0.259740
5       6  12.0  11  30  18.0  24  0.000000
6       7  14.0  13  35  21.0  28  0.545455
7       8  16.0  15  40  24.0  32  0.714286
8       9  18.0  17  45  27.0  36  0.844156
9      10  20.0  19  50  30.0  40  1.000000
10     11   NaN  21  55   NaN  44       NaN

In [20]:
path ="C:/Users/Guggi/Desktop/data analysis 1.xlsx"
df =pd.read_excel(path)
print(df)

    S. No     A   B   C     D   E  Length
0       1   2.0   1   5   3.0   4    45.0
1       2   4.0   3  10   6.0   8    43.0
2       3   6.0   5  15   9.0  12    66.0
3       4   8.0   7  20  12.0  16    78.0
4       5  10.0   9  25  15.0  20    32.0
5       6  12.0  11  30  18.0  24    12.0
6       7  14.0  13  35  21.0  28    54.0
7       8  16.0  15  40  24.0  32    67.0
8       9  18.0  17  45  27.0  36    77.0
9      10  20.0  19  50  30.0  40    89.0
10     11   NaN  21  55   NaN  44     NaN

In [22]:
# z-Score x(new)=(x(old) -mu)/sigma)        mu=Average of feature  and sigma - Standard deviation   Result =-3
df["Length"]=(df["Length"]-df["Length"].mean())/df["Length"].std()
df.head()

   S. No     A  B   C     D   E    Length
0      1   2.0  1   5   3.0   4 -0.477507
1      2   4.0  3  10   6.0   8 -0.562022
2      3   6.0  5  15   9.0  12  0.409896
3      4   8.0  7  20  12.0  16  0.916983
4      5  10.0  9  25  15.0  20 -1.026852